apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: backend
  labels:
    app: api-service
spec:
  type: LoadBalancer   
  selector:
    app: api-service
  ports:
    - port: 5200          # 외부에서 접근할 포트
      targetPort: 5200  # FastAPI 컨테이너가 실제 듣는 포트