apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: backend
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: 687436499847.dkr.ecr.ap-northeast-2.amazonaws.com/backend/api-service:latest
        ports:
        - containerPort: 5200
        env:
        - name: RAG_API_HOST
          value: "rag-service"  # EKS 내부 DNS로 rag-service 호출
        - name: RAG_API_PORT
          value: "5201"